[package]
name = "rust-image-processor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.2.4", default-features = false, features = ["napi8"] }
napi-derive = "3.2.4"

[build-dependencies]
napi-build = "2.1"
