/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 简单的加法函数 */
export declare function add(a: number, b: number): number

/** 检查文件是否存在 */
export declare function checkImageExists(imagePath: string): boolean

/** 检查文件是否是图片 */
export declare function checkImageFile(imagePath: string): boolean

/** 获取文件大小（字节） */
export declare function getFileSize(imagePath: string): bigint

/** 检查图片文件扩展名 */
export declare function getImageExtension(imagePath: string): string

/** 获取图片的基本信息 */
export declare function getImageInfo(imagePath: string): string

/** Hello World函数 */
export declare function hello(): string

/** 简单的图片重命名功能 */
export declare function renameImage(oldPath: string, newPath: string): boolean
