[server]
host = "127.0.0.1"
port = 8000
workers = 4
max_connections = 10000

[logging]
level = "info"
format = "json"
file_path = "logs/api-gateway.log"

[[routes]]
path = "/api/v1/users"
method = "GET"
upstream = "http://user-service:8080"
timeout = 30

[[routes]]
path = "/api/v1/products"
method = "GET|POST"
upstream = "http://product-service:8080"
timeout = 30

[[routes]]
path = "/api/v1/orders"
method = "*"
upstream = "http://order-service:8080"
timeout = 60
