[server]
host = "127.0.0.1"
port = 8000
workers = 4
max_connections = 10000

[logging]
level = "info"
format = "json"

[routes]
routes = [
  { path = "/api/test", method = "GET", upstream = "http://httpbin.org/json", timeout = 30 },
]
